spring.application.name=Hogwarts
spring.datasource.url=jdbc:postgresql://ad-postgre.cnvtou6we2bb.us-east-1.rds.amazonaws.com/hogwarts
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true